# Generated by Django 3.2.8 on 2021-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='distance_to_line',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='focus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='horizontal_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='sensor_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='vertical_angle',
            field=models.FloatField(default=0),
        ),
    ]
