version: '2.4'

services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v2.8.0
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  web:
    extends:
      file: common.yml
      service: web_base
    command: /commands/web.sh
    env_file: .uwsgi.env

  frontend:
    image: mf_frontend
    restart: unless-stopped

  nginx:
    image: mf_nginx
    restart: unless-stopped
    depends_on:
      - web
      - frontend
      - centrifugo
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs/nginx:/var/log/nginx
      - ./mounts/media:/webapp/media:ro
      - ./mounts/static:/webapp/static:ro